// Embedded, offline workspace. Graph-derived values are rendered with textContent only.
export const PAGE = String.raw`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Spindle — Metadata explorer</title><style>
:root{font-family:"Avenir Next",Avenir,system-ui,sans-serif;color:#18304b;background:#edf2f7;--blue:#165ac4;--line:#cbd8e5}*{box-sizing:border-box}body{margin:0}header{padding:22px 32px;background:#18304b;color:white;display:flex;align-items:center;justify-content:space-between}h1{font-size:25px;margin:0}header p{margin:4px 0 0;color:#bcd0e6}main{max-width:1500px;margin:auto;padding:28px}.toolbar{display:flex;gap:12px;flex-wrap:wrap;align-items:end;margin-bottom:20px}label{display:flex;flex-direction:column;gap:6px;font-size:14px;font-weight:600}select,input,button{font:inherit;border:1px solid #9fb5ca;border-radius:6px;padding:10px 12px;background:white;color:#18304b}button{cursor:pointer;background:var(--blue);color:white;border-color:var(--blue);font-weight:600}button.secondary{color:var(--blue);background:white}button:disabled{opacity:.5;cursor:default}:focus-visible{outline:3px solid #e6a63b;outline-offset:3px}.workspace{display:grid;grid-template-columns:minmax(300px,1fr) minmax(320px,1fr);gap:20px}.pane{background:white;border:1px solid var(--line);border-radius:9px;min-width:0;overflow:hidden}.pane h2{font-size:18px;margin:0;padding:18px 20px;border-bottom:1px solid var(--line)}#symbols{min-height:290px;max-height:65vh;overflow:auto}.symbol{display:block;text-align:left;background:white;border:0;border-bottom:1px solid #e2eaf1;border-radius:0;color:#18304b;width:100%;padding:15px 20px}.symbol:hover{background:#edf5ff}.symbol small{display:block;color:#536b83;font-weight:400;margin-top:6px;overflow-wrap:anywhere}.symbol strong{overflow-wrap:anywhere}.details{padding:20px;overflow:auto}pre{white-space:pre-wrap;word-break:break-word;line-height:1.55;font-family:ui-monospace,monospace;font-size:13px}#message{min-height:26px;margin:8px 0 15px;color:#465f78}.badge{background:#2e4864;padding:7px 12px;border-radius:20px;font-size:13px}.foot{padding:12px 20px;display:flex;gap:12px;align-items:center;border-top:1px solid var(--line)}.detail-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.empty{padding:24px;line-height:1.6;color:#536b83}details{margin-top:24px}summary{cursor:pointer;font-weight:600;margin-bottom:14px}@media(max-width:760px){main{padding:16px}header{padding:18px}.workspace{grid-template-columns:1fr}.toolbar>label{flex:1}input,select{max-width:100%}}
</style></head><body><header><div><h1>Spindle</h1><p>Explore the connections in your Salesforce metadata.</p></div><span class="badge">Read-only</span></header><main>
<form id="search" class="toolbar"><label>Project<select id="project" aria-label="Project"></select></label><label>Metadata type<select id="label"><option value="">All types</option><option>ApexClass</option><option>ApexMethod</option><option>ApexTrigger</option><option>Field</option><option>SObject</option><option>Flow</option><option>LwcBundle</option><option>PermissionSet</option></select></label><label>Symbol name<input id="pattern" placeholder="Account, Invoice__c, Service…"></label><button>Search metadata</button></form>
<div id="message" role="status" aria-live="polite"></div><div class="workspace"><section class="pane"><h2>Symbols</h2><div id="symbols"><p class="empty">Choose an indexed project to explore its metadata.</p></div><div class="foot"><button class="secondary" id="previous" disabled>Previous</button><button class="secondary" id="next" disabled>Next</button><span id="page"></span></div></section><section class="pane"><h2 id="detail-title">Connections & source</h2><div class="details"><div class="detail-actions"><button class="secondary" id="refs" disabled>Who references this?</button><button class="secondary" id="source" disabled>View source</button></div><pre id="detail">Select a symbol to inspect its references and source location.</pre></div></section></div>
<details><summary>Compare source snapshots</summary><div class="toolbar"><label>Baseline<select id="base"></select></label><label>Target<select id="target"></select></label><button id="compare">Compare metadata</button><button class="secondary" id="more-diff" disabled>More changes</button></div><pre id="diff">Index source retrieved from each org as separate projects, then compare them here. This does not query live orgs.</pre></details></main><script>
const $=id=>document.getElementById(id);let token=location.hash.slice(1)||sessionStorage.getItem('spindle-token');if(token)sessionStorage.setItem('spindle-token',token);history.replaceState(null,'',location.pathname);let offset=0,next=null,selected=null,selectedProject=null,diffOffset=0,diffNext=null,searchSequence=0;
async function api(tool,input={}){const response=await fetch('/api?'+new URLSearchParams({tool,input:JSON.stringify(input)}),{headers:{Authorization:'Bearer '+token}});const data=await response.json();if(!response.ok||data.error)throw Error(data.error||'Request failed');return data}
function error(e){$('message').textContent=e.message}function project(){return Number($('project').value)}function render(value,target='detail'){$(target).textContent=JSON.stringify(value,null,2)}
async function search(){if(!$('project').value)return;const sequence=++searchSequence;const projectId=project();selected=null;$('refs').disabled=true;$('source').disabled=true;try{$('message').textContent='Searching indexed metadata…';const text=$('pattern').value;const data=await api('search_graph',{project_id:projectId,...(text?{name_pattern:text.replace(/[.*+?^$\{\}()|[\]\\]/g,'\\$&')} : {}),...($('label').value?{label:$('label').value}:{}),offset,limit:25});if(sequence!==searchSequence)return;$('symbols').replaceChildren();for(const node of data.nodes){const b=document.createElement('button');b.className='symbol';const title=document.createElement('strong');title.textContent=node.qualifiedName;const note=document.createElement('small');note.textContent=node.label+' · '+(node.filePath||'No source file')+(node.startLine?':'+node.startLine:'');b.append(title,note);b.onclick=()=>{selected=node;selectedProject=projectId;render(node);$('refs').disabled=false;$('source').disabled=false;};$('symbols').append(b)}if(!data.nodes.length){const p=document.createElement('p');p.className='empty';p.textContent='No matching indexed symbols. Try another name or type.';$('symbols').append(p)}next=data.next_offset;$('next').disabled=!data.has_more;$('previous').disabled=offset===0;$('page').textContent='Page '+(offset/25+1);$('message').textContent=data.count+' symbols on this page. Results reflect indexed source.';}catch(e){error(e)}}
$('search').onsubmit=e=>{e.preventDefault();offset=0;search()};$('project').onchange=()=>{offset=0;selected=null;$('refs').disabled=true;$('source').disabled=true;search()};$('next').onclick=()=>{offset=next;search()};$('previous').onclick=()=>{offset=Math.max(0,offset-25);search()};
$('refs').onclick=async()=>{try{render(await api('trace_references',{project_id:selectedProject,start:{qualified_name:selected.qualifiedName,label:selected.label},direction:'inbound',depth:1}))}catch(e){error(e)}};
$('source').onclick=async()=>{try{const data=await api('get_source_snippet',{project_id:selectedProject,qualified_name:selected.qualifiedName});$('detail').textContent=data.source||JSON.stringify(data,null,2)}catch(e){error(e)}};
async function compare(){try{const data=await api('diff_projects',{base_project_id:Number($('base').value),target_project_id:Number($('target').value),limit:25,offset:diffOffset});render(data,'diff');diffNext=data.next_offset;$('more-diff').disabled=!data.has_more}catch(e){error(e)}}$('compare').onclick=()=>{diffOffset=0;compare()};$('more-diff').onclick=()=>{diffOffset=diffNext;compare()};
(async()=>{try{const data=await api('list_projects');for(const id of ['project','base','target'])for(const p of data.projects){const option=document.createElement('option');option.value=p.id;option.textContent=p.name+' — '+p.rootPath;$(id).append(option)}if(data.projects.length>1)$('target').selectedIndex=1;if(data.projects.length)search();else $('message').textContent='No projects indexed yet. Run sfdx-graph-mcp index /path/to/sfdx-project, then refresh.'}catch(e){error(e)}})();
</script></body></html>`;
